### ISSUE TITLE
Learning Strings and binary numbers

### ISSUE THREAD

**Issue by xavierleonardo** [rootEnginear/my-dcoder-solutions#1]
Hey, bro. How do you do?

O don't know If you work with PHP, but I wrote a code that pass in first three tests but fail on fourth, but O can't ser the test in the app. Do you think you cama Help?

Muito PHP code:
<?php
	 //php 7.0
	 $input=readline();
	 
	 $nums=explode(" ",$input);
	 
	 if(strpos($nums[0],$nums[1])){
 		echo 1;
 	} else {
 		echo 0;
 	}

 ?>

**Comment by rootEnginear** [comment]
Hello, Xavier.
I do apologize for late reply. I haven't been coding around PHP for a while but I'll try. If you are still stuck with this problem then try this:
```php
<?php
	fscanf(STDIN,"%[^\n]",$q);
	$s = explode(" ",$q);
	if(strpos($s[0],$s[1]) !== false){
		echo 1;
	}else{
		echo 0;
	}
?>
```
I have tried this and it passed all test cases. For your information, these are where I got help from:
- https://stackoverflow.com/questions/8097620/how-to-read-from-input-until-newline-is-found-using-scanf
- http://php.net/manual/en/function.explode.php
- https://stackoverflow.com/questions/4366730/how-do-i-check-if-a-string-contains-a-specific-word

I hope this will help you! Feel free to ask me if you want any help

**Comment by xavierleonardo** [comment]
Hi, rootEngineer. 

I want first to thank for your help. It really worked André passed all test case.

I want to appologize too, I'm now without any computer and I'm trying to continue with minimal ativities on the cel phone. I'm from Brazil and notice various wrong text in my question. I'm not a fluent english speaker and my cel dictionary "autocorrect/autocomplete" my texts.

Thanks again, mate.
